server.port=8081
# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (AIVEN CLOUD)
# ===============================
spring.datasource.url=jdbc:mysql://mysql-392f522d-fedelico134t-a89f.l.aivencloud.com:18879/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_VbOgrUA_4KrOaOWo0uL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# "update" creará las tablas en Aiven automáticamente basadas en tus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true